const Countries = require('../models/countries');
const connectDb = require('../configs/database/connectDb');
const mongoose = require('mongoose');

// load env
require('dotenv').config({ path: process.cwd() + '/.env.development' });

const countriesData = [
  {
    country_name: 'Canada',
    country_code: 'CA',
    states: [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Newfoundland and Labrador',
      'Northwest Territories',
      'Nova Scotia',
      'Nunavut',
      'Ontario',
      'Prince Edward Island',
      'Québec',
      'Saskatchewan',
      'Yukon',
    ],
  },
  {
    country_name: 'Dominican Republic',
    country_code: 'DO',
    states: [
      'Azua',
      'Bahoruco',
      'Baní',
      'Barahona',
      'Bonao',
      'Cotuí',
      'Dajabón',
      'Distrito Nacional',
      'El Seibo',
      'Elias Piña',
      'Hato Mayor',
      'Higüey',
      'Jimaní',
      'La Romana',
      'La Vega',
      'Mao',
      'Moca',
      'Monte Cristi',
      'Monte Plata',
      'Nagua',
      'Neiba',
      'Pedernales',
      'Puerto Plata',
      'Sabaneta',
      'Salcedo',
      'Samaná',
      'San Cristóbal',
      'San Francisco de Macorís',
      'San José de Ocoa',
      'San Juan',
      'San Pedro de Macorís',
      'Santiago',
      'Santo Domingo Este',
    ],
  },
  {
    country_name: 'Mexico',
    country_code: 'MX',
    states: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Coahuila',
      'Colima',
      'Distrito Federal',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'Michoacán',
      'Morelos',
      'México',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas',
    ],
  },
  {
    country_name: 'Puerto Rico',
    country_code: 'PR',
    states: [
      'Aguadilla',
      'Arecibo',
      'Bayamon',
      'Carolina',
      'Guayama',
      'Humacao',
      'Ponce',
      'San Juan',
    ],
  },
  {
    country_name: 'United States',
    country_code: 'US',
    states: [
      'Alabama',
      'Alaska',
      'American Samoa',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'District Of Columbia',
      'Federated States Of Micronesia',
      'Florida',
      'Georgia',
      'Guam',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Marshall Islands',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Northern Mariana Islands',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Palau',
      'Pennsylvania',
      'Puerto Rico',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virgin Islands',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
  },
  {
    country_name: 'Venezuela',
    country_code: 'VE',
    states: [
      'Amazonas',
      'Anzoátegui',
      'Apure',
      'Aragua',
      'Barinas',
      'Bolívar',
      'Carabobo',
      'Cojedes',
      'Delta Amacuro',
      'Distrito Capital',
      'Falcón',
      'Guárico',
      'Lara',
      'Miranda',
      'Monagas',
      'Mérida',
      'Nueva Esparta',
      'Portuguesa',
      'Sucre',
      'Trujillo',
      'Táchira',
      'Vargas',
      'Yaracuy',
      'Zulia',
    ],
  },
];

// connect db
connectDb();

const seed = async () => {
  await Countries.deleteMany();
  const inserted = await Countries.collection.insertMany(countriesData);
  console.log('inserted ', inserted);
};

(async () => {
  await seed();
  mongoose.disconnect();
})();
